#include "../include/isr.h"
#include "../include/kernel.h"

void __attribute__((cdecl)) isr_c_handler(interrupt_frame* ctx){
    while(1);
    asm volatile(
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
        "mov rax, 67\n"
        "nop\n"
    );
    printd("Interrupt %d TRIGGERED\n", ctx->interrupt);
    while(1);
}






